# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-modify_date',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='description text', max_length=100, verbose_name='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='post',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify Date'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=django.utils.timezone.now, help_text='title alias', unique=True, verbose_name='SLUG'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='blog_post',
        ),
    ]
